### ISSUE TITLE
Media queries request

### ISSUE THREAD

**Issue by AviusX** [FrigidSec/FrigidSec.github.io#2]
We need media queries to scale the background better on mobile devices. 
Currently the background does not scale well on mobile devices and a large part of the logo gets cut off.

**Comment by Saket-Upadhyay** [comment]
@FrigidSec/webdevteam

**Comment by abhishek2x** [comment]
Image is already responsive but if it looks ugly, we need to modify the image such that the main logo scale is reduced.

**Comment by Saket-Upadhyay** [comment]
Okay we will push a new background in this case

**Comment by Saket-Upadhyay** [comment]
one solution is to remove the lower banner font. we will try that

**Comment by Saket-Upadhyay** [comment]
@FrigidSec/webdevteam check commit b1c6c04561e4f8cc688480bfb614db2ef87cf4ec in **source** branch.
@abhishek2x please build and deploy using this.

Tested using Firefox Dev. Mode Device Compatibility check, Looks good.

**Comment by abhishek2x** [comment]
Resolved and Deployed
